export const MICROSOFT_LOGIN_START = 'MICROSOFT_LOGIN_START';
export const MICROSOFT_LOGIN_ERROR = 'MICROSOFT_LOGIN_ERROR';
export const MICROSOFT_LOGIN_SUCCESS = 'MICROSOFT_LOGIN_SUCCESS';
export const MICROSOFT_LOGIN_CANCEL = 'MICROSOFT_LOGIN_CANCEL';
